### Create a new ContactPerson
POST http://localhost:3000/contact-persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "firstName": "Jane",
  "lastName": "Doe",
  "designation": "HR Manager",
  "emailAddress": "test6@gmail.com",
  "phoneNumber": "+254770137226",
  "primaryContact": true,
  "investorProfileId": 2
}

### Grant profile access ContactPerson
POST http://localhost:3000/contact-persons/grant-access
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "contactPersonId": 4,
  "investorProfileId": 2
}

### Revoke profile access ContactPerson
POST http://localhost:3000/contact-persons/revoke-access
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "contactPersonId": 4,
  "investorProfileId": 2
}

### Get all ContactPersons
GET http://localhost:3000/contact-persons
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### Get investor profiles paginated
GET http://localhost:3000/investor-profiles?page=5&limit=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get a specific ContactPerson
GET http://localhost:3000/contact-persons/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Update a ContactPerson
PATCH http://localhost:3000/contact-persons/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "hasAccess": true
}

### Delete a ContactPerson
DELETE http://localhost:3000/contact-persons/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Grant profile access Contact Person Prod
POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/contact-persons/grant-access
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "contactPersonId": 4,
  "investorProfileId": 3
}
