### Create a new financial information record.
POST http://localhost:3000/finances
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "companyId": 1,
    "year": 2023,
    "costOfSales": 5000,
    "ebitda": 2000,
    "ebit": 1000,
    "taxes": 500,
    "revenues": [ 1 ],
    "opex": [ 1 ]
}

### Find All financial information.
GET http://localhost:3000/finances
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Find All financial information by companyId.
GET http://localhost:3000/finances/company/365
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Find financial information by id.
GET http://localhost:3000/finances/37
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Update financial information record.
PUT http://localhost:3000/finances/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "year": 2023,
    "costOfSales": 1000,
    "ebitda": 1000,
    "ebit": 500,
    "taxes": 100,
    "revenues": [ 1, 2 ],
    "opex": [ 1, 2]
}

### Add notes to the financial information record.
PUT http://localhost:3000/finances/1/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "notes": "Agreed to reduce the cost of sales by 50%"
}

### Approve a financial information record.
PUT http://localhost:3000/finances/1/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Reject a financial information record.
PUT http://localhost:3000/finances/1/revoke
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Delete a financial information record.
DELETE http://localhost:3000/finances/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
