### Match companies based on investor profile criteria
GET http://localhost:3000/matchmaking/companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Match companies based on investor profile criteria by investorProfileId
GET http://localhost:3000/matchmaking/companies/13
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Match companies based on investor profile criteria by investorProfileId
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/matchmaking/companies/35
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Match companies based on investor profile criteria
GET http://localhost:3000/matchmaking/investor-profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Mark a company as interesting (investorProfileId/companyId)
POST http://localhost:3000/matchmaking/interesting/2/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Mark a company as not interesting (investorProfileId/companyId)
POST http://localhost:3000/matchmaking/decline/2/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "declineReasons": ["No possibility for further growth.", "Not interested in the sector."]
}

### Connect with a company (investorProfileId/companyId)
POST http://localhost:3000/matchmaking/connect/2/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Disconnect from a connected company (investorProfileId/companyId)
POST http://localhost:3000/matchmaking/disconnect/1/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get interesting companies for an investor profile (investor profile id)
GET http://localhost:3000/matchmaking/interested/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get declined companies for an investor profile (investor profile id)
GET http://localhost:3000/matchmaking/declined/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get connected companies for an investor profile (investor profile id)
GET http://localhost:3000/matchmaking/connected/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get investors interested in a company (company id)
GET http://localhost:3000/matchmaking/investors/interested/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get investors connected to a company (company id)
GET http://localhost:3000/matchmaking/investors/connected/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Match decline reason.
POST http://localhost:3000/matchmaking/7/decline-reasons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "reason": "No possibility for further growth."
}

### Company filtering
POST http://localhost:3000/matchmaking/search-companies
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "countries": ["Kenya", "Rwanda"],
  "businessSectors": ["Agriculture", "Healthcare", "Venture Capital"],
  "businessSubsectors": ["Farming", "Pharmacy"],
  "productsAndServices": "Software",
  "registrationStructures": ["Limited Company", "Partnership"],
  "yearsOfOperation": "0 - 1 years",
  "growthStages": ["Seed", "Series A"],
  "numberOfEmployees": "1-10 employees",
  "fullTimeBusiness": false
}

### Download matchmaking CSV
GET http://localhost:3000/matchmaking/download-csv/2?status=interesting
Content-Type: text/csv
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### Download matchmaking CSV prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/download-csv/2?status=interesting
Content-Type: text/csv
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Search companies based on investor profile criteria and text (investorProfileId, status, query)
GET http://localhost:3000/matchmaking/search-matches/2?status=interesting&q=kenya
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Search companies based on investor profile criteria and text prod (investorProfileId, status, query)
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/matchmaking/search-matches/35?status=interesting&q=kenya
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Search companies as admin (status, query)
GET http://localhost:3000/matchmaking/search-matches?status=declined&q=kenya
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
