### Data drilling (Only use one parameter example "countries":["Rwanda"])
POST http://localhost:3000/statistics/stats-filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "countries":["Rwanda"],
  "growthStages": ["Start-up pre-revenue"],
  "businessSectors": ["Technology"],
  "useOfFunds": ["Working capital"]
}

### Get user statistics
GET http://localhost:3000/statistics/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

### Get user statistics
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/statistics/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get matchmaking statistics
GET http://localhost:3000/statistics/matchmaking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total matchmaking statistics
GET http://localhost:3000/statistics/matchmaking/totals
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get matchmaking statistics
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/statistics/matchmaking
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get matchmaking statistics per investor/company (investorId/companyId)
GET http://localhost:3000/statistics/matchmaking/8?role=company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get matchmaking statistics per investor/company (investorId/companyId)
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/statistics/matchmaking/35?role=investor
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get special criteria statistics
GET http://localhost:3000/statistics/special-criteria
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get special criteria statistics per investor (investorId)
GET http://localhost:3000/statistics/special-criteria/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### Get special criteria statistics prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/statistics/special-criteria
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get special criteria statistics per investor (investorId) prod
GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/statistics/special-criteria/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of businesses registered.
GET http://localhost:3000/statistics/businesses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of businesses per stage.
GET http://localhost:3000/statistics/businesses-stage
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of businesses per fund raise.
GET http://localhost:3000/statistics/businesses-fund
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of businesses per country.
GET http://localhost:3000/statistics/businesses-country
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of Investors registered
GET http://localhost:3000/statistics/investors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of Investors and companies per sector.
GET http://localhost:3000/statistics/sectors-stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get number of Investors by minimum or maximum funding.(minimumFunding / maximumFunding)
GET http://localhost:3000/statistics/investors-funds?type=maximumFunding
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get Total number of Investors and companies by use of funds.
GET http://localhost:3000/statistics/funding-stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get statistics for all connection requests by investorId.
GET http://localhost:3000/statistics/requests/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get subscription statistics.
GET http://localhost:3000/statistics/subscription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get bookings statistics.
GET http://localhost:3000/statistics/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get payments statistics.
GET http://localhost:3000/statistics/payments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
