### Assign subscription to a User (userId, subscriptionId)
POST http://localhost:3000/subscriptions/19/2
Content-Type: application/json

### Validate User subscription (userId)
GET http://localhost:3000/subscriptions/validate/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

### Create booking

POST http://localhost:3000/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionId": 6
}

### Create booking prod

GET http://api.capitalconnect.africa/subscriptions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionId": 1
}

### Create booking

POST http://api.capitalconnect.africa/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionId": 2
}