### Assign subscription to a User (userId, subscriptionId)
POST http://localhost:3000/subscriptions/19/2
Content-Type: application/json

### Validate User subscription (userId)
GET http://localhost:3000/subscriptions/validate/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

### Fetch User subscription (userId)
GET http://localhost:3000/subscriptions/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

### Fetch User subscription (userId) prod
GET http://api.capitalconnect.africa/subscriptions/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

### Subscribe

POST http://localhost:3000/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionTierId": 6
}

### Upgrade

POST http://localhost:3000/subscriptions/upgrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionTierId": 6
}

### Subscribe prod

POST http://api.capitalconnect.africa/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionTierId": 2
}

### Upgrade prod

POST http://api.capitalconnect.africa/subscriptions/upgrade
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "subscriptionTierId": 6
}