###
# Create section
POST http://localhost:3000/subsections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9



{
    "name": "Section 700",
    "sectionId": 7,
    "description": "Section 700 description"
}

###
# Get sub section

GET http://localhost:3000/subsections/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get sub sections

GET http://localhost:3000/subsections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get sub sections paginated

GET http://localhost:3000/subsections?page=1&count=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Update section

PUT http://localhost:3000/subsections/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
    "name": "Updated Sub Section 1",
    "description": "Updated Sub Section 1 description"
}

###
# Delete section

DELETE http://localhost:3000/subsections/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

###
# Get section questions

GET http://localhost:3000/subsections/2/questions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9