### Click referral link
PUT http://localhost:3000/referrals/metrics/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

{
    "clicks": true
}

### Visit a page
PUT http://localhost:3000/referrals/metrics/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
Content-Type: application/json

{
    "visits": true
}

### Sign up with referral Id
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "test4@gmail.com",
    "password": "pass1234",
    "firstName": "Mkuu",
    "hasAcceptedTerms": true,
    "referralToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
}

### Get user referrals
GET http://localhost:3000/referrals/user/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

### Get referrals
GET http://localhost:3000/referrals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9


### Get stats
GET http://localhost:3000/referrals/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
