### Create meeting

POST http://localhost:3000/webex/create
Content-Type: application/json
code: YmQ1NTA0YjgtZDRjNS00YTAyLTlhMTctZTQ4MjNiZjI4OGI4NWRlYTNiNzEtYzVh_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

{
  "title": "Project Meeting",
  "start": "2024-12-25T08:00:00.000Z",
  "end": "2024-12-25T09:00:00.000Z",
  "timezone": "UTC",
  "invitees": [
    { "email": "attendee@example.com",  "displayName": "Attendee One test" },
    { "email": "attendee1@example.com", "displayName": "Attendee One" },
    { "email": "attendee2@example.com", "displayName": "Attendee Two" },
    { "email": "vickyjr88@gmail.com", "displayName": "Vicky Junior" }
  ],
  "bookingId": 8
}

### Authorize

GET http://localhost:3000/webex/authorization/initiation

### Get meeting

GET http://localhost:3000/webex/865ca0f68b694cebb0025f4084435723
Content-Type: application/json
code: OWU0ZWEwYmYtZGUwMC00NjY0LTkzOGQtMjBlYTEzOTc4NjljZmM2ZThkNmItY2Ez_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

### Get authorizations codeas

GET http://localhost:3000/webex/authorizations
Content-Type: application/json
code: ZmFjMGFhNjMtMTk5MC00ZDM0LWEwOTAtNWI4MmQwMzAzYzQ5NTMxNTQ2NDQtZjk4_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7### Get authorizations codeas

### Delete authorizations codeas

DELETE http://localhost:3000/webex/authorizations
Content-Type: application/json
code: ZmFjMGFhNjMtMTk5MC00ZDM0LWEwOTAtNWI4MmQwMzAzYzQ5NTMxNTQ2NDQtZjk4_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

### Create Metting Prod

POST https://capitalconnect-0060e0fb0eb4.herokuapp.com/webex/create
Content-Type: application/json
code: NjgxOTBhZmMtYTg1My00NDlmLTgwZmQtOWEwM2Y5OGFjMGZiMTdjMTk2Y2QtNjk0_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

{
  "title": "Project Meeting",
  "start": "2024-12-25T08:00:00.000Z",
  "end": "2024-12-25T09:00:00.000Z",
  "timezone": "UTC",
  "invitees": [
    { "email": "attendee@example.com",  "displayName": "Attendee One test" },
    { "email": "attendee1@example.com", "displayName": "Attendee One" },
    { "email": "attendee2@example.com", "displayName": "Attendee Two" },
    { "email": "vickyjr88@gmail.com", "displayName": "Vicky Junior" }
  ],
  "bookingId": 8
}

### Authorize prod

GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/webex/authorization/initiation


### Get meeting prod (meeting id)

GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/webex/cebd5c382d234975805723958efff95c
Content-Type: application/json
code: ZmFjMGFhNjMtMTk5MC00ZDM0LWEwOTAtNWI4MmQwMzAzYzQ5NTMxNTQ2NDQtZjk4_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

### Refresh token
POST https://webexapis.com/v1/access_token
Content-Type: application/json

{
  "grant_type": "refresh_token",
  "refresh_token": "MWYxNjZiMzktNTU2My00Mjk3LTgyYmQtNDg3YjQ0ZWI3YzJiNjlhNzNlMDUtMDY1_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7",
  "client_id": "C17aefb8e8aee8bcd617512aba43f0479a46NDg3YjQ0ZWI3YzJiNc88af611a3eefdd8a",
  "client_secret": "5ea5d72adf96a6901a658043433f603da383dNDg3YjQ0ZWI3YzJiN4b440b5415"
}

### Get authorizations codeas

GET https://capitalconnect-0060e0fb0eb4.herokuapp.com/webex/authorizations
Content-Type: application/json
code: ZmFjMGFhNjMtMTk5MC00ZDM0LWEwOTAtNWI4MmQwMzAzYzQ5NTMxNTQ2NDQtZjk4_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7

### Delete authorizations codeas

DELETE https://capitalconnect-0060e0fb0eb4.herokuapp.com/webex/authorizations
Content-Type: application/json
code: ZmFjMGFhNjMtMTk5MC00ZDM0LWEwOTAtNWI4MmQwMzAzYzQ5NTMxNTQ2NDQtZjk4_P0A1_bdd2aed2-da17-481d-bd6f-b43037ee90b7
